---
title: "final"
author: "Allison Dong"
date: "5/19/2020"
output: html_document
---
## Zooming Into Our State
```{r  message=FALSE, echo=TRUE}
library(httr)
library(stringr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(scales)
library(cowplot)
library(tidyverse)

# Get the data from the repository
us_confirmed <-read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")

us_death <-read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")

 # Create a dataset with data for california
us_confirmed_ca <- us_confirmed %>% filter(str_detect(us_confirmed$Province_State, 'California'))
us_death_ca <- us_death %>% filter(str_detect(us_death$Province_State, 'California'))

# Delete the other unnecessary columns
us_confirmed_ca_con <- select(us_confirmed_ca, -UID, -iso2, -iso3, -code3, -FIPS, -Admin2, -Country_Region, -Combined_Key, -Lat, -Long_)
us_death_ca_con <- select(us_death_ca, -UID, -iso2, -iso3, -code3, -FIPS, -Admin2, -Country_Region, -Combined_Key, -Lat, -Long_, -Population)

# Sum the number of confirmed and death for california
us_confirmed_ca_grouped <- us_confirmed_ca_con %>%
  group_by(Province_State) %>%
  summarise_all(funs(sum))

us_death_ca_grouped <- us_death_ca_con %>%
  group_by(Province_State) %>%
  summarise_all(funs(sum))

# Change the date format to normal date format
us_confirmed_ca_grouped_rearrange <- 
   gather(us_confirmed_ca_grouped, key = Date, value = Cases, -Province_State)
us_confirmed_ca_grouped_rearrange <- data.frame(us_confirmed_ca_grouped_rearrange, stringsAsFactors = FALSE) %>%
  mutate(Date=as.Date(Date,format = "X%m.%d.%y")) 

us_death_ca_grouped_rearrange <- 
   gather(us_death_ca_grouped, key = Date, value = Cases, -Province_State)
us_death_ca_grouped_rearrange <- data.frame(us_death_ca_grouped_rearrange, stringsAsFactors = FALSE) %>%
  mutate(Date=as.Date(Date,format = "X%m.%d.%y")) 

# Plot 
plot1 <- ggplot() +
  geom_point(data = us_confirmed_ca_grouped_rearrange, aes(x = Date, y= Cases, color ="blue")) +
  geom_point(data = us_death_ca_grouped_rearrange, aes(x = Date, y= Cases, color = "red"))+
  scale_x_date(labels = date_format("%Y-%m-%d"), breaks = "month") +
  geom_vline(xintercept = as.numeric(as.Date("2020-03-19")), color = "black") +
  labs(
    title ="California's Trajectory for COVID-19") +
  scale_colour_hue("California Total", labels = c("Confirmed", "Deaths")) 

# Delete the other unnecessary columns
us_confirmed_city_con <- select(us_confirmed_ca, -UID, -iso2, -iso3, -code3, -FIPS, -Province_State, -Country_Region, -Combined_Key, -Lat, -Long_)

# Rank the data by the city has highest cases 
confirmed_cases_city <- arrange(us_confirmed_city_con, -us_confirmed_city_con$X5.20.20)

# Get the top 3 cities
top_3_confirmed <- filter(confirmed_cases_city[1:3, ])

# Change the date format to normal date format
confirmed_cases_city_rearrange <- 
   gather(top_3_confirmed, key = Date, value = Cases, -Admin2)
confirmed_cases_city_rearrange <- data.frame(confirmed_cases_city_rearrange, stringsAsFactors = FALSE) %>%
  mutate(Date=as.Date(Date,format = "X%m.%d.%y")) 

# Plot 
plot2 <- ggplot(data = confirmed_cases_city_rearrange) +
  geom_point(
  mapping = aes(x = Date, y= Cases,color = Admin2)) +
  scale_x_date(labels = date_format("%Y-%m-%d")) +
  geom_vline(xintercept = as.numeric(as.Date("2020-03-19")), color = "black") +
  labs(
    title ="California's top three city trajectories for confirmations",
    color = "Top Confirmed Cities" ) 

plot_grid(plot1, plot2, ncol = 1, align = 'v')
```
## Digging Deeper
```{r DD}
# Delete column
confirmed_population <- select(us_confirmed, -UID, -iso2, -iso3, -code3, -FIPS, -Country_Region, -Combined_Key, -Lat, -Long_, -Province_State)

death <- select(us_death, -UID, -iso2, -iso3, -code3, -FIPS, -Country_Region, -Combined_Key, -Lat, -Long_, -Province_State, -Admin2)

# Change the date format to normal date format 
#and change from wide to long
confirmed_population_rearrange <- 
   gather(confirmed_population, key = Date, value = Confirmed, -Admin2)
confirmed_population_rearrange <- data.frame(confirmed_population_rearrange, stringsAsFactors = FALSE) %>%
  mutate(Date=as.Date(Date,format = "X%m.%d.%y"))

death_rearrange <- 
   gather(death, key = Date, value = Death, -Population)
death_rearrange <- data.frame(death_rearrange, stringsAsFactors = FALSE) %>%
  mutate(Date=as.Date(Date,format = "X%m.%d.%y"))

# Plot
plot.population <- ggplot(data = data.frame(confirmed=confirmed_population_rearrange$Confirmed, Population=us_death$Population)) +
  geom_point(
  mapping = aes(x = Population, y= confirmed)) +
  scale_x_continuous(labels=scales::comma, trans = log2_trans()) +
  scale_y_continuous(labels=scales::comma, trans = log2_trans()) +
  labs(
    title ="Confirmations Vs. Population", y = "Confirmation Counts") 

##
plot.con_death <- ggplot(data = data.frame(Confirmed=confirmed_population_rearrange$Confirmed, Death=death_rearrange$Death)) +
  geom_point(
  mapping = aes(x = Confirmed, y= Death)) +
  scale_x_continuous(labels=scales::comma, trans = log2_trans()) +   
  scale_y_continuous(labels=scales::comma, trans = log2_trans()) +
  labs(
    title ="Deaths VS. Confirmations", x= "Confirmed Counts", y="Deaths Counts") 
  
plot_grid(plot.population, plot.con_death, align = 'v')
```
